version: "3"
services:
  #ちなみにnodeはphp-fpm内にnodeを入れる
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html/

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    depends_on:
      - php-fpm
    ports:
      - 13306:3306
    build:
        context: "./docker/mysql"
        dockerfile: "Dockerfile"    
    #volumes:
    # もし永続化させたいときにはこの部分を記載
    #  - ./data/postgres:/var/lib/postgresql/data
    environment:
      - MYSQL_DATABASE: admin_table
      - MYSQL_USER: user
      - MYSQL_PASSWORD: password
      - MYSQL_ROOT_PASSWORD: root

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025