workflows:
  version: 2
  sample_workflow:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - test
jobs:
  test:
    docker:
      - image: cimg/php:8.1.7
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist 
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths: 
            - vendor
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - run: cp .env.example .env
      - run:
          name: touch database.sqlite
          command: touch database.sqlite
      - run:
          name: php sqlite test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: cimg/php:8.1.7
    steps:
      - checkout
      - run:
          name: deploy heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APPNAME.git