workflows:
  version: 2
orbs: 
  heroku: circleci/heroku@1.2.6

sample_workflow:
  jobs:
    - test
    - deploy:
        filters:
          branches:
            only:
              - main
        requires:
          - test

jobs:
  test:
    docker:
      - image: cimg/php:8.1.7-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist 
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths: 
            - vendor
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - run: cp .env.example .env
      - run:
          name: touch database.sqlite
          command: touch database.sqlite
      - run:
          name: php sqlite test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: cimg/php:8.1.7-browsers
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_APPNAME
      # 現在は使わなそう
      #- run:
      #    name: DB migration
      #    command: heroku run php artisan migrate --app $HEROKU_APPNAME